copy samples to pages

diff --git a/.github/workflows/gh_pages.yaml b/.github/workflows/gh_pages.yaml
--- a/.github/workflows/gh_pages.yaml
+++ b/.github/workflows/gh_pages.yaml
@@ -25,32 +25,48 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
       
-      - run: git submodule update --init --recursive
+      - name: Delete samples and test
+        run: |
+          rm -rf ./examples/*.pdf
+          rm -rf ./test/*.pdf
       
       - name: Download font assets
-        # working-directory: ./docs-shiroa
-        # use fonts in stable releases
         run: |
           mkdir -p assets/fonts/
           curl -L https://github.com/Myriad-Dreamin/shiroa/releases/download/v0.1.0/charter-font-assets.tar.gz | tar -xvz -C assets/fonts/
           curl -L https://github.com/Myriad-Dreamin/shiroa/releases/download/v0.1.5/source-han-serif-font-assets.tar.gz | tar -xvz -C assets/fonts/
       
       - name: Download & install shiroa
-        # working-directory: ./docs-shiroa
         run: |
           curl -L https://github.com/Myriad-Dreamin/shiroa/releases/download/v0.3.1-rc4/shiroa-x86_64-unknown-linux-gnu.tar.gz | tar -xvz
           chmod +x shiroa-x86_64-unknown-linux-gnu/shiroa
           sudo cp shiroa-x86_64-unknown-linux-gnu/shiroa /usr/bin/shiroa
-
-      # - name: Build Book
-      #   working-directory: ./docs-shiroa
-      #   run: |
-      #     shiroa build --font-path ./assets/typst-fonts/ --font-path ./assets/fonts/ --path-to-root /typst-g-exam/ --workspace . g-exam-doc
       
       - name: Build Book
         run: |
           shiroa build --font-path assets/fonts --path-to-root /typst-g-exam/ --workspace . docs-shiroa/g-exam-doc --mode static-html
           
+      - uses: typst-community/setup-typst@v4
+
+      - name: Compile Typst examples to PDF
+        shell: bash
+        run: |
+          for archivo in $(ls -1 ./examples/*.typ); do
+              echo "$archivo"
+              typst compile $archivo --root .
+              
+              if [ $? -eq 0 ]; then
+                  echo "Compilación exitosa: $archivo"
+              else
+                  echo "Error al compilar: $archivo"
+              fi
+          done
+
+      - name: Copy examples PDF
+        shell: bash
+        run: |
+          cp ./examples/*.pdf ./docs-shiroa/dist/assets/
+
       - name: Setup Pages
         uses: actions/configure-pages@v5
 
